### ISSUE TITLE
Create a docker-compose file to launch f-API and query tool

### ISSUE THREAD

**Issue by surchs** [neurobagel/federation-api#33] opened 2023-11-20 17:50 UTC
I want to be able to copy / use a docker-compose.yml file so that I can

- [ ] docker compose up a correctly configured f-API and query tool at once
- [ ] easily update / relaunch this stack in the future (e.g. if new local nodes are added)

**Comment by alyssadai** [comment] 2023-12-05 17:49
Duplicate of https://github.com/neurobagel/recipes/issues/1

**Closed by alyssadai** 2023-12-05 17:49 UTC
